name: Monitor ANVISA Diario

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Baixar o codigo do repositorio
      uses: actions/checkout@v3

    - name: Configurar o Python no servidor
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar bibliotecas necessarias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Executar o Robo de Monitoramento
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python monitor_anvisa.py
